sudo: required
services:
  - docker
language: python
python: 2.7
before_install:
  - wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
  - sudo dpkg -i vagrant_1.8.1_x86_64.deb
  - for image in default production; do docker pull philpep/test-driven-infrastructure-example:$image; done
  - vagrant up --no-provision --provider=docker
install:
  - pip install tox
script:
  - tox
